version 23.2R2.21;
system {
    host-name R5-IGR1;
    root-authentication {
        encrypted-password "<REDACTED>"; ## SECRET-DATA
    }
    services {
        ssh;
        web-management {
            http {
                interface fxp0.0;
            }
            https {
                system-generated-certificate;
                interface fxp0.0;
            }
        }
    }
    syslog {
        file interactive-commands {
            interactive-commands any;
        }
        file messages {
            any any;
            authorization info;
        }
    }
    license {
        autoupdate {
            url https://ae1.juniper.net/junos/key_retrieval;
        }
    }
}
security {
    pki {
        ca-profile ISRG_Root_X1 {
            ca-identity ISRG_Root_X1;
            pre-load;
        }
        ca-profile Lets_Encrypt {
            ca-identity Lets_Encrypt;
            enrollment {
                url https://acme-v02.api.letsencrypt.org/directory;
            }
        }
    }
    forwarding-options {
        family {
            mpls {
                mode packet-based;
            }
            iso {
                mode packet-based;
            }
        }
    }
    screen {
        ids-option untrust-screen {
            icmp {
                ping-death;
            }
            ip {
                source-route-option;
                tear-drop;
            }
            tcp {
                syn-flood {
                    alarm-threshold 1024;
                    attack-threshold 200;
                    source-threshold 1024;
                    destination-threshold 2048;
                    queue-size 2000; ## Warning: 'queue-size' is deprecated
                    timeout 20;
                }
                land;
            }
        }
    }
}
interfaces {
    ge-0/0/1 {
        unit 0 {
            family inet {
                address 10.3.5.2/30;
            }
            family iso;
        }
    }
    ge-0/0/2 {
        unit 0 {
            family inet {
                address 10.5.6.1/30;
            }
            family iso;
        }
    }
    ge-0/0/3 {
        unit 0 {
            family inet {
                address 10.5.10.2/30;
            }
        }
    }
    ge-0/0/4 {
        unit 0 {
            family inet {
                address 10.5.20.2/30;
            }
        }
    }
    fxp0 {
        unit 0;
    }
    lo0 {
        unit 0 {
            family inet {
                address 5.5.5.5/32;
            }
            family iso {
                address 10.0000.0000.0000.0005.00;
            }
        }
    }
}
policy-options {
    policy-statement NEXT-HOP-SELF {
        term 1 {
            then {
                next-hop self;
            }
        }
    }
}
protocols {
    bgp {
        group iBGP {
            local-address 5.5.5.5;
            export NEXT-HOP-SELF;
            peer-as 1000;
            neighbor 3.3.3.3;
            neighbor 4.4.4.4;
            neighbor 6.6.6.6;
            neighbor 1.1.1.1;
        }
        group ebgp_AS3000 {
            local-address 10.5.10.2;
            peer-as 3000;
            neighbor 10.5.10.1;
        }
        group ebgp_AS4000 {
            local-address 10.5.20.2;
            peer-as 4000;
            neighbor 10.5.20.1;
        }
    }
    isis {
        interface ge-0/0/1.0;
        interface ge-0/0/2.0 {
            point-to-point;
        }
        interface lo0.0;
    }
}
routing-options {
    autonomous-system 1000;
}